---
title: Eva
timezone: Europe/Amsterdam
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
header: Eva van der Weide
short_title: Eva
copyright: "@ 2018 Sem Postma All rights Reserved"
defaults: 
  - 
    scope:
      path: "./*.markdown"
      type: "pages"
    values:
      layout: "page"
      image:
        width: 100
        height: 100
        image: ""
keywords: Polyism Studio Sem Postma Echo Sierra Studio Web Software Code Programming
  Hub
description: Web, app and tooling development and graphic design studio. View all
  websites made by Echo Sierra Studio and contact us if your interested.
theme_color: "#fb5353"
baseurl: 
abbrv: ESS
dribbble_username: 
facebook_username: 
flickr_username: 
github_username: 
instagram_username: 
linkedin_username: 
pinterest_username: 
twitter_username: 
youtube_username: 
googleplus_username: 
facebook:
  app_id: 
  publisher: 
  admins: 
webmaster_verifications:
  google: 
  bing: 
  alexa: 
  yandex: 
  baidu: 
twitter:
  username: 
sass:
  style: compressed
  sass_dir: _sass
plugins:
- jekyll-feed
- jekyll-sitemap
theme: minima
markdown: kramdown
author:
  name: Sem Postma
  from: Oosterhout, Noord Brabant, The Netherlands
  role: Developer
  email: sem.postma@gmail.com
designer:
  name: Sem Postma
  from: Oosterhout, Noord Brabant, The Netherlands
  role: Developer
  email: sem.postma@gmail.com
google_analytics: 
